(110, 'Jigglypuff', 'When it sings, its enemy falls asleep. Jigglypuff can happily sing for hours on end.', 'Sing', '10', 'Steel', 'Dark', 1, 39, 1, 10, 1),
(60, 'Zubat', 'Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.', 'Leech Life', '20', 'Psychic', 'Grass', 1, 41, 1, 6, 1),
(120, 'Oddish', 'During the day, it stays in the cold underground to avoid the sun. It grows by bathing in moonlight.', 'Absorb', '30', 'Fire', 'Water', 1, 43, 1, 5, 1),
(50, 'Paras', 'Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.', 'Scratch', '20', 'Fire', 'Water', 2, 46, 1, 5, 1),
(70, 'Venonat', 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.', 'Poison Powder', '10', 'Psychic', 'Grass', 1, 48, 1, 5, 1),
(90, 'Meowth', 'Adores round objects. It wanders the streets on a nightly basis to look for dropped loose change.', 'Pay Day', '20', 'Fighting', 'Psychic', 1, 52, 1, 1, 1),
(100, 'Psyduck', 'While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers.', 'Confusion', '40', 'Electric', 'Fighting', 2, 54, 1, 3, 1),
(60, 'Mankey', 'Extremely quick to anger. It could be docile one moment then thrashing away the next instant.', 'Karate Chop', '30', 'Psychic', 'Grass', 1, 56, 1, 6, 1),
(120, 'Growlithe', 'Very protective of its territory. It will bark and bite to repel intruders from its space.', 'Flame Wheel', '40', 'Water', 'Grass', 1, 58, 1, 2, 1),
(80, 'Poliwag', 'The direction of the spiral on the belly differs by area. It is more adept at swimming than walking.', 'Water Gun', '20', 'Electric', 'Fighting', 1, 60, 1, 3, 1),
(90, 'Machoke', 'Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.', 'Seismic Toss', '50', 'Psychic', 'Grass', 2, 67, 1, 6, 2),
(140, 'Victreebel', 'Lures prey with the sweet aroma of honey. Swallowed whole, the prey is melted in a day, bones and all.', 'Acid', '60', 'Fire', 'Water', 3, 71, 1, 5, 3),
(50, 'Tentacool', 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.', 'Poison Sting', '20', 'Psychic', 'Grass', 1, 72, 1, 3, 1),
(100, 'Graveler', 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.', 'Rock Throw', '30', 'Water', 'Electric', 2, 75, 1, 6, 2),
(110, 'Golem', 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.', 'Explosion', '60', 'Water', 'Electric', 3, 76, 1, 6, 3),
(70, 'Ponyta', 'Its hooves are ten times harder than diamond. It can trample anything completely flat in little time.', 'Stomp', '30', 'Water', 'Grass', 1, 77, 1, 2, 1),
(90, 'Slowpoke', 'Incredibly slow and sluggish. It is quite content to loll about without worrying about the time.', 'Headbutt', '20', 'Electric', 'Fighting', 1, 79, 1, 3, 1),
(60, 'Magnemite', 'Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves.', 'Thunder Shock', '20', 'Ground', 'Steel', 1, 81, 1, 4, 1),
(80, 'Farfetchd', 'The plant stalk it holds is its weapon. The stalk is used like a sword to cut all sorts of things.', 'Slash', '30', 'Electric', 'Fighting', 1, 83, 1, 1, 1),
(120, 'Dodrio', 'Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.', 'Tri Attack', '40', 'Electric', 'Fighting', 3, 85, 1, 1, 3),
(110, 'Seel', 'The protruding horn on its head is very hard. It is used for bashing through thick ice.', 'Headbutt', '20', 'Electric', 'Fighting', 1, 86, 1, 3, 1),
(80, 'Grimer', 'Appears in filthy areas. It thrives by sucking up polluted sludge that is pumped out of factories.', 'Sludge', '20', 'Psychic', 'Grass', 1, 88, 1, 6, 1),
(90, 'Shellder', 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.', 'Clamp', '30', 'Electric', 'Fighting', 1, 90, 1, 3, 1),
(140, 'Gengar', 'On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing.', 'Shadow Ball', '60', 'Psychic', 'Grass', 3, 94, 1, 6, 3),
(60, 'Onix', 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.', 'Rock Throw', '30', 'Water', 'Electric', 1, 95, 1, 6, 1),
(90, 'Drowzee', 'Puts enemies to sleep, then eats their dreams. Occasionally gets sick from eating bad dreams.', 'Hypnosis', '10', 'Bug', 'Dark', 1, 96, 1, 6, 1),
(100, 'Krabby', 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.', 'Vice Grip', '20', 'Electric', 'Fighting', 1, 98, 1, 3, 1),
